---
- name: Create Group
  ansible.builtin.shell:
    cmd: |
      # Create the spool directory for recording transfer from BigBlueButton
      mkdir -p /mnt/scalelite-recordings/var/bigbluebutton/spool
      chown 1000:2000 /mnt/scalelite-recordings/var/bigbluebutton/spool
      chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/spool

      # Create the temporary (working) directory for recording import
      mkdir -p /mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite
      chown 1000:2000 /mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite
      chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/recording/scalelite

      # Create the directory for published recordings
      mkdir -p /mnt/scalelite-recordings/var/bigbluebutton/published
      chown 1000:2000 /mnt/scalelite-recordings/var/bigbluebutton/published
      chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/published

      # Create the directory for unpublished recordings
      mkdir -p /mnt/scalelite-recordings/var/bigbluebutton/unpublished
      chown 1000:2000 /mnt/scalelite-recordings/var/bigbluebutton/unpublished
      chmod 0775 /mnt/scalelite-recordings/var/bigbluebutton/unpublished