---
- name: Create folder for SSL
  ansible.builtin.file:
    name: "/local/certs"
    state: directory

- name: Upload SSL Certificate
  ansible.builtin.copy:
    src: "{{ ssl_crt_file }}"
    dest: "/local/certs/fullchain.pem"

- name: Upload SSL Key
  ansible.builtin.copy:
    src: "{{ ssl_key_file }}"
    dest: "/local/certs/privkey.pem"
