---
- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install EFS Prerequisite RPMS
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
  with_items:
    - git
    - binutils
    - stunnel4

# See https://docs.aws.amazon.com/efs/latest/ug/installing-amazon-efs-utils.html#installing-other-distro
# stunnel4 required.
- name: Build/Install efs utilities
  ansible.builtin.shell:
    cmd: |
      cd ~
      git clone https://github.com/aws/efs-utils
      cd efs-utils
      ./build-deb.sh
      apt install -y ./build/amazon-efs-utils*deb
    executable: /bin/bash

- name: Create folder for EFS
  ansible.builtin.file:
    path: /mnt/scalelite-recordings
    state: directory

- name: Mount EFS
  ansible.posix.mount:
    path: /mnt/scalelite-recordings
    state: mounted
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
    fstype: nfs4
    src: "{{ efs_dns }}:/"

- name: Uninstall build tools
  ansible.builtin.apt:
    name: "{{item}}"
    state: absent
  with_items:
    - git
    - binutils
