---
- name: Update bbb servers
  hosts: "*"
  become: yes

  tasks:
  - name: Update package cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Set hostname
    ansible.builtin.hostname:
      name: "{{hostname}}"
      use: systemd

  - name: Mount EFS
    ansible.builtin.include_role:
      name: efs

  - name: Configure BBB
    ansible.builtin.include_role:
      name: bbb


