---
- name: Update Scalelite servers
  hosts: "*"
  become: yes

  tasks:
  - name: Package Updates
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: yes

  - name: Set hostname
    ansible.builtin.hostname:
      name: "{{hostname}}"
      use: systemd

  - name: Setup EFS
    ansible.builtin.include_role:
      name: efs

  - name: Setup Scalelite
    ansible.builtin.include_role:
      name: sl

